# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 01fdba63ac6ae74144f70df71e70fb2b08708663f6f37507e35c9112833d0a91dfacf0c04633a2373c16fb4c8369467c878a804cb59817f5baf8b5d6c674c300

test:
  secret_key_base: 7d2d5a2ca3c61c711b17f1497317eb0314b235f2a0d0843cd7cd5458e55c1bea36119a43b6c1313ee0a930862bc002f96f4acda3a740a0cbc23fd45da809783c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
